version: "3.8"

services:
  service:
    build: ./service
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - service
      - db
  db:
    image: postgres:15
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_DB: digit_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      DATABASE_URL: postgres://user:password@db:5432/digit_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Run init script at startup
volumes:
  pg_data: